export const HomeObjOne={
    id:'about',
    lightBg:false,
    lightText:true,
    lightTextDesc:true,
    topLine:'Premium Bank',
    headLine:'Unlimited transactions with zero fees',
    description:'Get acees to out exclusive app that allows you to send unlimited transactions without getting charged any fees',
    buttonLable:'Get Started',
    imgStart:true,
    img:require('../../images/svg-1.svg').default,
    alt:'Car',
    dark:true,
    primary:true,
    darkText:false,
}
export const HomeObjTwo={
    id:'signup',
    lightBg:false,
    lightText:true,
    lightTextDesc:true,
    topLine:'Premium Bank',
    headLine:'Unlimited transactions with zero fees',
    description:'Get acees to out exclusive app that allows you to send unlimited transactions without getting charged any fees',
    buttonLable:'Get Started',
    imgStart:false,
    img:require('../../images/svg-2.svg').default,
    alt:'Car',
    dark:true,
    primary:true,
    darkText:false,
}
export const HomeObjThree={
    id:'discover',
    lightBg:true,
    lightText:false,
    lightTextDesc:false,
    topLine:'Unlimited access',
    headLine:'Unlimited transactions with zero fees',
    description:'Get acees to out exclusive app that allows you to send unlimited transactions without getting charged any fees',
    buttonLable:'Learn More',
    imgStart:true,
    img:require('../../images/svg-3.svg').default,
    alt:'Car',
    dark:false,
    primary:false,
    darkText:false,
}

